### ISSUE TITLE
Add 'wheel' package to the list of prerequisites

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetApp/ONTAP-Tools-for-VMware-vSphere#1]
Saw the following additional requirement when installing requirements.txt.

Using legacy 'setup.py install' for vsphere-automation-sdk, since package 'wheel' is not installed.

[admin@ansible ansible]$ pip3 install -r ~/.ansible/collections/ansible_collections/community/vmware/requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/vmware/vsphere-automation-sdk-python.git (from -r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2))
  Cloning https://github.com/vmware/vsphere-automation-sdk-python.git to /tmp/pip-req-build-wp7f_9x_
Requirement already satisfied (use --upgrade to upgrade): vsphere-automation-sdk==1.86.0 from git+https://github.com/vmware/vsphere-automation-sdk-python.git in /home/admin/.local/lib/python3.9/site-packages (from -r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2))
Requirement already satisfied: pyVmomi>=6.7 in /usr/local/lib/python3.9/site-packages (from -r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 1)) (8.0.2.0.1)
Requirement already satisfied: lxml>=4.3.0 in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (5.1.0)
Requirement already satisfied: vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.44.0)
Requirement already satisfied: vcenter-bindings@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vcenter-bindings/vcenter_bindings-4.2.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vcenter-bindings/vcenter_bindings-4.2.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.2.0)
Requirement already satisfied: vapi-common-client@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-common-client/vapi_common_client-2.44.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-common-client/vapi_common_client-2.44.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.44.0)
Requirement already satisfied: vmwarecloud-aws@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vmwarecloud-aws/vmwarecloud_aws-1.64.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vmwarecloud-aws/vmwarecloud_aws-1.64.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (1.64.0)
Requirement already satisfied: nsx-python-sdk@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/nsx-python-sdk/nsx_python_sdk-4.1.2.0.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-wp7f_9x_/lib/nsx-python-sdk/nsx_python_sdk-4.1.2.0.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.1.2.0.0)
Requirement already satisfied: nsx-policy-python-sdk@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/nsx-policy-python-sdk/nsx_policy_python_sdk-4.1.2.0.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-wp7f_9x_/lib/nsx-policy-python-sdk/nsx_policy_python_sdk-4.1.2.0.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.1.2.0.0)
Requirement already satisfied: nsx-vmc-policy-python-sdk@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/nsx-vmc-policy-python-sdk/nsx_vmc_policy_python_sdk-4.1.2.0.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-wp7f_9x_/lib/nsx-vmc-policy-python-sdk/nsx_vmc_policy_python_sdk-4.1.2.0.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.1.2.0.0)
Requirement already satisfied: nsx-vmc-aws-integration-python-sdk@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/nsx-vmc-aws-integration-python-sdk/nsx_vmc_aws_integration_python_sdk-4.1.2.0.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-wp7f_9x_/lib/nsx-vmc-aws-integration-python-sdk/nsx_vmc_aws_integration_python_sdk-4.1.2.0.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.1.2.0.0)
Requirement already satisfied: vmwarecloud-draas@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vmwarecloud-draas/vmwarecloud_draas-1.23.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vmwarecloud-draas/vmwarecloud_draas-1.23.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (1.23.0)
Requirement already satisfied: six>=1.7.3 in /usr/local/lib/python3.9/site-packages (from pyVmomi>=6.7->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: pyOpenSSL in /home/admin/.local/lib/python3.9/site-packages (from vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (24.0.0)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.9/site-packages (from vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: setuptools in /usr/lib/python3.9/site-packages (from vcenter-bindings@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vcenter-bindings/vcenter_bindings-4.2.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (50.3.2)
Requirement already satisfied: cryptography<43,>=41.0.5 in /home/admin/.local/lib/python3.9/site-packages (from pyOpenSSL->vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (42.0.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib64/python3.9/site-packages (from requests<3.0.0,>=2.0.0->vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: cffi>=1.12; platform_python_implementation != "PyPy" in /home/admin/.local/lib/python3.9/site-packages (from cryptography<43,>=41.0.5->pyOpenSSL->vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: pycparser in /home/admin/.local/lib/python3.9/site-packages (from cffi>=1.12; platform_python_implementation != "PyPy"->cryptography<43,>=41.0.5->pyOpenSSL->vapi-runtime@ file://localhost//tmp/pip-req-build-wp7f_9x_/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.21)
Using legacy 'setup.py install' for vsphere-automation-sdk, since package 'wheel' is not installed.
[admin@ansible ansible]$ 

[admin@ansible ansible]$ pip3 install wheel
Defaulting to user installation because normal site-packages is not writeable
Collecting wheel
  Downloading wheel-0.42.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 3.7 MB/s 
Installing collected packages: wheel
Successfully installed wheel-0.42.0

[admin@ansible ansible]$ pip3 install -r ~/.ansible/collections/ansible_collections/community/vmware/requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/vmware/vsphere-automation-sdk-python.git (from -r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2))
  Cloning https://github.com/vmware/vsphere-automation-sdk-python.git to /tmp/pip-req-build-kggtof2w
Requirement already satisfied (use --upgrade to upgrade): vsphere-automation-sdk==1.86.0 from git+https://github.com/vmware/vsphere-automation-sdk-python.git in /home/admin/.local/lib/python3.9/site-packages (from -r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2))
Requirement already satisfied: pyVmomi>=6.7 in /usr/local/lib/python3.9/site-packages (from -r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 1)) (8.0.2.0.1)
Requirement already satisfied: lxml>=4.3.0 in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (5.1.0)
Requirement already satisfied: vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.44.0)
Requirement already satisfied: vcenter-bindings@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vcenter-bindings/vcenter_bindings-4.2.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-kggtof2w/lib/vcenter-bindings/vcenter_bindings-4.2.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.2.0)
Requirement already satisfied: vapi-common-client@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-common-client/vapi_common_client-2.44.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-common-client/vapi_common_client-2.44.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.44.0)
Requirement already satisfied: vmwarecloud-aws@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vmwarecloud-aws/vmwarecloud_aws-1.64.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-kggtof2w/lib/vmwarecloud-aws/vmwarecloud_aws-1.64.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (1.64.0)
Requirement already satisfied: nsx-python-sdk@ file://localhost//tmp/pip-req-build-kggtof2w/lib/nsx-python-sdk/nsx_python_sdk-4.1.2.0.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-kggtof2w/lib/nsx-python-sdk/nsx_python_sdk-4.1.2.0.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.1.2.0.0)
Requirement already satisfied: nsx-policy-python-sdk@ file://localhost//tmp/pip-req-build-kggtof2w/lib/nsx-policy-python-sdk/nsx_policy_python_sdk-4.1.2.0.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-kggtof2w/lib/nsx-policy-python-sdk/nsx_policy_python_sdk-4.1.2.0.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.1.2.0.0)
Requirement already satisfied: nsx-vmc-policy-python-sdk@ file://localhost//tmp/pip-req-build-kggtof2w/lib/nsx-vmc-policy-python-sdk/nsx_vmc_policy_python_sdk-4.1.2.0.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-kggtof2w/lib/nsx-vmc-policy-python-sdk/nsx_vmc_policy_python_sdk-4.1.2.0.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.1.2.0.0)
Requirement already satisfied: nsx-vmc-aws-integration-python-sdk@ file://localhost//tmp/pip-req-build-kggtof2w/lib/nsx-vmc-aws-integration-python-sdk/nsx_vmc_aws_integration_python_sdk-4.1.2.0.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-kggtof2w/lib/nsx-vmc-aws-integration-python-sdk/nsx_vmc_aws_integration_python_sdk-4.1.2.0.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (4.1.2.0.0)
Requirement already satisfied: vmwarecloud-draas@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vmwarecloud-draas/vmwarecloud_draas-1.23.0-py2.py3-none-any.whl from file://localhost//tmp/pip-req-build-kggtof2w/lib/vmwarecloud-draas/vmwarecloud_draas-1.23.0-py2.py3-none-any.whl in /home/admin/.local/lib/python3.9/site-packages (from vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (1.23.0)
Requirement already satisfied: six>=1.7.3 in /usr/local/lib/python3.9/site-packages (from pyVmomi>=6.7->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: pyOpenSSL in /home/admin/.local/lib/python3.9/site-packages (from vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (24.0.0)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.9/site-packages (from vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: setuptools in /usr/lib/python3.9/site-packages (from vcenter-bindings@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vcenter-bindings/vcenter_bindings-4.2.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (50.3.2)
Requirement already satisfied: cryptography<43,>=41.0.5 in /home/admin/.local/lib/python3.9/site-packages (from pyOpenSSL->vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (42.0.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (3.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib64/python3.9/site-packages (from requests<3.0.0,>=2.0.0->vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: cffi>=1.12; platform_python_implementation != "PyPy" in /home/admin/.local/lib/python3.9/site-packages (from cryptography<43,>=41.0.5->pyOpenSSL->vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: pycparser in /home/admin/.local/lib/python3.9/site-packages (from cffi>=1.12; platform_python_implementation != "PyPy"->cryptography<43,>=41.0.5->pyOpenSSL->vapi-runtime@ file://localhost//tmp/pip-req-build-kggtof2w/lib/vapi-runtime/vapi_runtime-2.44.0-py2.py3-none-any.whl->vsphere-automation-sdk==1.86.0->-r /home/admin/.ansible/collections/ansible_collections/community/vmware/requirements.txt (line 2)) (2.21)
Building wheels for collected packages: vsphere-automation-sdk
  Building wheel for vsphere-automation-sdk (setup.py) ... done
  Created wheel for vsphere-automation-sdk: filename=vsphere_automation_sdk-1.86.0-py3-none-any.whl size=2339 sha256=355dbca20fa9435ec987c1b851597df29662312d196557f30158b6b47d0e8627
  Stored in directory: /tmp/pip-ephem-wheel-cache-lg7qu1tw/wheels/95/78/cd/cca5ecd9a3fe87775b445b0a2e5c5a51e5f5f032625c0f7c52
Successfully built vsphere-automation-sdk

**Comment by kaminis85** [comment]
Updated the prerequisites with the "pip3 install wheel" command
Thanks @netapp-jyhshing
